#!/usr/bin/env ruby

require 'telegram/bot'

# token:
# 1. Write your TOKEN value into "token" variable or
# 2. Create a local file "hiden.token" with your TOKEN value inside
token = `cat /etc/bot19/hiden.token`.strip
bot_username = '@Rodriguez19_bot'

puts "[INFO] Running bot #{$0}..."

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    puts " => #{message.text}"
    if message.text == "/hello"
      bot.api.send_message(chat_id: message.chat.id, text: "Hello Word!")
    elsif message.text == "/time"
      t = Time.now
      bot.api.send_message(chat_id: message.chat.id, text: t.strftime("%H:%M:%S"))
    elsif message.text == "/date"
      t = Time.now
      bot.api.send_message(chat_id: message.chat.id, text: t.strftime("%d/%m/%Y"))
    elsif message.text == "/byebye"
      bot.api.send_message(chat_id: message.chat.id, text: "Bye bye!")
    end
  end
end
